-- generated by hypr-wallpaper (wallust) — machine-local, git-ignored.
--
-- Consumed by config/hypr/lua/appearance.lua, which falls back to its own
-- built-in palette if this file is absent or malformed. COLOURS ONLY —
-- gaps / rounding / blur / animations stay in appearance.lua.
--
-- Semantic mapping (see config/wallust/templates/quickshell-colors.json for
-- the full token set):
--   active_border   = accent  ->  accent darkened      (the focused window)
--   inactive_border = background darkened + translucent (barely there)
--   shadow          = near-black tinted by the wallpaper
return {
  active_border   = {
    "rgba({{ color5 | saturate(0.20) | strip }}ff)",
    "rgba({{ color5 | darken(0.22) | strip }}dd)",
  },
  inactive_border = "rgba({{ background | darken(0.10) | strip }}aa)",
  shadow          = 0xcc{{ background | darken(0.55) | strip }},
}
